name: Selenium Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: ./mvnw clean test --batch-mode
    - uses: actions/upload-artifact@v2
      with:
        name: reports
        path: target/surefire-reports/
